import { describe, expect, it } from 'vitest';
import { implementationCommentBody } from '@/pipeline/implementation.js';
import { planCommentBody, splitChildCommentBody } from '@/pipeline/planning.js';
import { isSwarmGeneratedBody, SWARM_GENERATED_FOOTER, swarmMarker } from '@/scm/swarm-origin.js';

describe('SWARM-origin markers', () => {
	// Comments SWARM already posted must keep matching, so these two renderings are
	// pinned byte-for-byte: `DELIVERY_MARKER` (src/integrations/scm/github/client.ts)
	// and `planDeliveryMarker` (src/pipeline/planning.ts) are now built from
	// `swarmMarker`, and drift here would silently un-mark historical comments.
	it('renders the delivery markers exactly as they have always been emitted', () => {
		expect(swarmMarker('delivery', 'run-42')).toBe('<!-- swarm-delivery:run-42 -->');
		expect(swarmMarker('planning-delivery', 'run-42')).toBe(
			'<!-- swarm-planning-delivery:run-42 -->',
		);
		expect(SWARM_GENERATED_FOOTER).toBe('_Generated by SWARM._');
	});

	it('recognizes a body carrying a hidden delivery marker', () => {
		expect(isSwarmGeneratedBody(`## 👀 Review\n\n${swarmMarker('delivery', 'run-42')}`)).toBe(true);
		expect(isSwarmGeneratedBody(`plan\n\n${swarmMarker('planning-delivery', 'run-42')}`)).toBe(
			true,
		);
	});

	it('recognizes a body carrying the generated footer, including a phase-qualified one', () => {
		expect(isSwarmGeneratedBody(`## ⚠️ SWARM run failed\n\n---\n${SWARM_GENERATED_FOOTER}`)).toBe(
			true,
		);
		expect(
			isSwarmGeneratedBody(
				'## 🚀 Implementation complete\n\n---\n_Generated by SWARM (Implementation phase). This item has moved to **In review**._',
			),
		).toBe(true);
	});

	it('recognizes real phase comment bodies produced by SWARM', () => {
		const plan = planCommentBody('step one', false, 'run-42');
		expect(isSwarmGeneratedBody(plan)).toBe(true);

		const impl = implementationCommentBody('https://github.com/jkwiecien/swarm/pull/449');
		expect(isSwarmGeneratedBody(impl)).toBe(true);

		const child = splitChildCommentBody(
			{
				id: '1',
				title: 'Parent',
				url: 'https://github.com/jkwiecien/swarm/issues/1',
				description: '',
				labels: [],
				assignees: [],
			},
			[],
			2,
			3,
			true,
		);
		expect(isSwarmGeneratedBody(child)).toBe(true);

		const bareMarker = '## Custom header\n\n<!-- swarm-delivery:run-100 -->';
		expect(isSwarmGeneratedBody(bareMarker)).toBe(true);
	});

	it('does not claim a plain human comment, quote-reply, or inline signature mention', () => {
		// The federated regression this replaces: the operator's own account is the
		// implementer identity, so an author check dropped their hand-written
		// comments. Content, not authorship, decides.
		expect(isSwarmGeneratedBody('Please also handle the empty-list case.')).toBe(false);
		expect(isSwarmGeneratedBody('SWARM generated a plan for this, but I disagree.')).toBe(false);
		expect(isSwarmGeneratedBody('I think _Generated by SWARM._ is neat')).toBe(false);
		expect(isSwarmGeneratedBody(undefined)).toBe(false);
		expect(isSwarmGeneratedBody('')).toBe(false);

		// GitHub-shaped quote-reply quoting a prior SWARM comment line-by-line
		const plan = planCommentBody('step one', false, 'run-42');
		const quoteReply = plan
			.split('\n')
			.map((line) => `> ${line}`)
			.join('\n')
			.concat('\n\nI disagree with step 1.');
		expect(isSwarmGeneratedBody(quoteReply)).toBe(false);
	});
});
