/**
 * "Did SWARM write this?" — the provider-neutral origin test behind comment loop
 * prevention (`GitHubRouterAdapter.isSelfAuthored`, issue #443).
 *
 * **Why not the comment's author.** SWARM used to answer this by matching the
 * comment's author against its own persona logins (`isSwarmBot`). Under the
 * federated model (ADR-004 §2, issue #396) the implementer credential is the
 * *worker operator's own* GitHub token, so the author of a SWARM comment is a
 * plain user account: the gate started dropping that operator's hand-written
 * comments as if SWARM had authored them, while failing to recognise comments
 * SWARM delivered through *another* operator's account. Author identity stopped
 * carrying the signal — the comment's own content has to.
 *
 * **What does.** Every comment SWARM posts carries one of two stable
 * self-identifying strings, and both are built from the constants here, so a
 * producer and this detector cannot drift apart:
 *
 * - a hidden {@link swarmMarker} — the per-delivery idempotency markers
 *   `<!-- swarm-delivery:… -->` (`src/integrations/scm/github/client.ts`) and
 *   `<!-- swarm-planning-delivery:… -->` (`src/pipeline/planning.ts`);
 * - the visible {@link SWARM_GENERATED_FOOTER} (or a phase-qualified variant of
 *   {@link SWARM_GENERATED_SIGNATURE}) on the phase, split-child, and
 *   failure/mergeability comments, which carry no per-delivery marker.
 *
 * The gate is only as good as that coverage, so a new SWARM comment body must
 * append one of the two.
 *
 * A dependency-free leaf module rather than part of `delivery.ts`: the router
 * adapter and the GitHub client are on the reading end, and neither should pull
 * the delivery module's `node:child_process`/`node:fs` surface in for three
 * strings.
 */

/** Opening bytes shared by every hidden SWARM marker. */
export const SWARM_MARKER_PREFIX = '<!-- swarm-';

/** A hidden SWARM marker: `<!-- swarm-<kind>:<id> -->`. */
export function swarmMarker(kind: string, id: string): string {
	return `${SWARM_MARKER_PREFIX}${kind}:${id} -->`;
}

/**
 * Leading text shared by the plain footer and its phase-qualified variants
 * (`_Generated by SWARM (Planning phase). …_`) — what {@link isSwarmGeneratedBody}
 * matches, so a phase can extend the sentence without escaping the gate.
 */
export const SWARM_GENERATED_SIGNATURE = '_Generated by SWARM';

/** The plain attribution footer for a SWARM comment with nothing phase-specific to add. */
export const SWARM_GENERATED_FOOTER = `${SWARM_GENERATED_SIGNATURE}._`;

/**
 * Whether `body` is a comment body SWARM produced (see the header above).
 *
 * **Quote-reply handling.** When a human replies to a SWARM comment in GitHub,
 * GitHub's quote-reply format includes the prior comment line-by-line with each
 * line prefixed by `> `. To prevent an operator's quote-reply from being dropped
 * as self-authored, `isSwarmGeneratedBody` splits the body by lines, skips any
 * blockquoted line (lines whose trimmed content starts with `>`), and checks only
 * non-quoted lines for a hidden marker or a line starting with
 * {@link SWARM_GENERATED_SIGNATURE}.
 */
export function isSwarmGeneratedBody(body: string | undefined): boolean {
	if (!body) return false;
	const lines = body.split('\n');
	for (const line of lines) {
		const trimmed = line.trim();
		if (trimmed.startsWith('>')) continue;
		if (trimmed.includes(SWARM_MARKER_PREFIX) || trimmed.startsWith(SWARM_GENERATED_SIGNATURE)) {
			return true;
		}
	}
	return false;
}
