import { describe, expect, it } from 'vitest';

import { adfToPlainText, textToAdf } from '@/integrations/pm/jira/adf.js';
import { isSwarmGeneratedBody, swarmMarker } from '@/scm/swarm-origin.js';

describe('adfToPlainText', () => {
	it('reads a nested document as blocks, keeping marked-up runs on one line', () => {
		const document = {
			version: 1,
			type: 'doc',
			content: [
				{ type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Goal' }] },
				{
					type: 'paragraph',
					content: [
						{ type: 'text', text: 'Ship ' },
						{ type: 'text', text: 'the thing', marks: [{ type: 'strong' }] },
						{ type: 'text', text: ' today.' },
					],
				},
				{
					type: 'bulletList',
					content: [
						{
							type: 'listItem',
							content: [{ type: 'paragraph', content: [{ type: 'text', text: 'first' }] }],
						},
						{
							type: 'listItem',
							content: [{ type: 'paragraph', content: [{ type: 'text', text: 'second' }] }],
						},
					],
				},
				{
					type: 'codeBlock',
					attrs: { language: 'ts' },
					content: [{ type: 'text', text: 'const a = 1;\nconst b = 2;' }],
				},
			],
		};

		expect(adfToPlainText(document)).toBe(
			[
				'Goal',
				'',
				'Ship the thing today.',
				'',
				'first',
				'second',
				'',
				'const a = 1;',
				'const b = 2;',
			].join('\n'),
		);
	});

	it('recurses into an unknown node type instead of dropping its text', () => {
		const document = {
			type: 'doc',
			content: [
				{
					type: 'panel',
					attrs: { panelType: 'info' },
					content: [{ type: 'paragraph', content: [{ type: 'text', text: 'inside a panel' }] }],
				},
				{
					type: 'swarmUnknownExtension',
					content: [{ type: 'paragraph', content: [{ type: 'text', text: 'still readable' }] }],
				},
			],
		};

		expect(adfToPlainText(document)).toBe('inside a panel\n\nstill readable');
	});

	it('reads a hard break as a line break inside one paragraph', () => {
		const document = {
			type: 'doc',
			content: [
				{
					type: 'paragraph',
					content: [
						{ type: 'text', text: 'line one' },
						{ type: 'hardBreak' },
						{ type: 'text', text: 'line two' },
					],
				},
			],
		};

		expect(adfToPlainText(document)).toBe('line one\nline two');
	});

	it.each([
		[undefined],
		[null],
		[''],
		[0],
		[[]],
		[{}],
	])('reads absent content as an empty string (%s)', (value) => {
		expect(adfToPlainText(value)).toBe('');
	});

	it('passes a plain string through, for a v2-shaped or webhook body', () => {
		expect(adfToPlainText('already plain text')).toBe('already plain text');
	});
});

describe('textToAdf', () => {
	it('wraps each line as its own paragraph, blank lines included', () => {
		expect(textToAdf('first\n\nsecond')).toEqual({
			version: 1,
			type: 'doc',
			content: [
				{ type: 'paragraph', content: [{ type: 'text', text: 'first' }] },
				{ type: 'paragraph', content: [] },
				{ type: 'paragraph', content: [{ type: 'text', text: 'second' }] },
			],
		});
	});

	it('produces a valid empty document for empty text', () => {
		expect(textToAdf('')).toEqual({
			version: 1,
			type: 'doc',
			content: [{ type: 'paragraph', content: [] }],
		});
	});
});

describe('round trip', () => {
	it('preserves a hidden SWARM marker, so comment idempotency and loop prevention survive', () => {
		const body = [
			'Planning complete.',
			'',
			'_Generated by SWARM (Planning phase)._',
			'',
			swarmMarker('planning-delivery', '2490f13f-23e4-477c-88be-c15d496d7a2f'),
		].join('\n');

		const roundTripped = adfToPlainText(textToAdf(body));

		expect(roundTripped).toContain(
			'<!-- swarm-planning-delivery:2490f13f-23e4-477c-88be-c15d496d7a2f -->',
		);
		expect(roundTripped).toBe(body);
		expect(isSwarmGeneratedBody(roundTripped)).toBe(true);
	});
});
